export const INCREMENT_TEST_DATA = 'INCREMENT_TEST_DATA';
export const FETCH_ALL_POSTS = 'FETCH_ALL_POSTS';
export const CREATE_POST = 'CREATE_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';
export const SET_CURRENT_POST = 'SET_CURRENT_POST';
export const REMOVE_CURRENT_POST = 'REMOVE_CURRENT_POST';
